apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task
  name: api-server-deployment
  labels:
    app: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: sgkrishnan2020/api-server-k8s-task:5.0
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: api-config
