apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: task
spec:
  type: LoadBalancer
  externalIPs: ["34.229.213.135"]
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
