
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task
  name: mysql-deployment
  labels:
    app: mysql-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: sgkrishnan2020/mysql-sample-task-db
        ports:
        - containerPort: 3306
